
-- Create careers table with RIASEC profiles
CREATE TABLE public.careers (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  riasec_profile JSONB NOT NULL DEFAULT '{}',
  suggested_majors TEXT[] NOT NULL DEFAULT '{}',
  required_skills TEXT[] NOT NULL DEFAULT '{}',
  salary_range TEXT,
  industry TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

-- Public read access for all authenticated users
ALTER TABLE public.careers ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Anyone authenticated can view careers"
ON public.careers FOR SELECT
USING (auth.role() = 'authenticated');

-- Seed career data with RIASEC profiles
INSERT INTO public.careers (title, description, riasec_profile, suggested_majors, required_skills, salary_range, industry) VALUES
('Software Engineer', 'Design, develop, and maintain software systems and applications. Work with teams to solve complex technical problems.', '{"R": 0.5, "I": 0.9, "A": 0.4, "S": 0.3, "E": 0.3, "C": 0.6}', ARRAY['Computer Science', 'Software Engineering', 'Information Technology'], ARRAY['Programming', 'Problem Solving', 'System Design', 'Version Control'], '$70,000 - $150,000', 'Technology'),
('Data Scientist', 'Analyze large datasets to extract insights, build predictive models, and drive data-informed decisions.', '{"R": 0.3, "I": 0.95, "A": 0.3, "S": 0.3, "E": 0.4, "C": 0.7}', ARRAY['Computer Science', 'Statistics', 'Mathematics', 'Data Science'], ARRAY['Python', 'Machine Learning', 'Statistics', 'Data Visualization'], '$80,000 - $160,000', 'Technology'),
('UX/UI Designer', 'Create intuitive and visually appealing user interfaces. Conduct user research and design digital experiences.', '{"R": 0.3, "I": 0.5, "A": 0.95, "S": 0.6, "E": 0.3, "C": 0.3}', ARRAY['Graphic Design', 'Human-Computer Interaction', 'Fine Arts', 'Psychology'], ARRAY['Figma', 'User Research', 'Prototyping', 'Visual Design'], '$60,000 - $130,000', 'Design & Creative'),
('Marketing Manager', 'Plan and execute marketing strategies, manage campaigns, and analyze market trends to drive business growth.', '{"R": 0.2, "I": 0.5, "A": 0.6, "S": 0.5, "E": 0.9, "C": 0.5}', ARRAY['Marketing', 'Business Administration', 'Communications'], ARRAY['Digital Marketing', 'Analytics', 'Content Strategy', 'Leadership'], '$65,000 - $140,000', 'Business'),
('Civil Engineer', 'Design and oversee construction of infrastructure projects including bridges, roads, and buildings.', '{"R": 0.95, "I": 0.7, "A": 0.3, "S": 0.3, "E": 0.4, "C": 0.6}', ARRAY['Civil Engineering', 'Structural Engineering', 'Construction Management'], ARRAY['AutoCAD', 'Project Management', 'Structural Analysis', 'Mathematics'], '$65,000 - $120,000', 'Engineering'),
('Clinical Psychologist', 'Assess and treat mental health conditions. Provide therapy and counseling to individuals and groups.', '{"R": 0.1, "I": 0.7, "A": 0.4, "S": 0.95, "E": 0.3, "C": 0.4}', ARRAY['Psychology', 'Clinical Psychology', 'Counseling'], ARRAY['Therapeutic Techniques', 'Assessment', 'Active Listening', 'Empathy'], '$60,000 - $130,000', 'Healthcare'),
('Financial Analyst', 'Evaluate financial data, create forecasts, and advise organizations on investment and budgeting decisions.', '{"R": 0.2, "I": 0.7, "A": 0.1, "S": 0.3, "E": 0.6, "C": 0.95}', ARRAY['Finance', 'Accounting', 'Economics', 'Business Administration'], ARRAY['Financial Modeling', 'Excel', 'Data Analysis', 'Risk Assessment'], '$60,000 - $120,000', 'Finance'),
('Graphic Designer', 'Create visual content for brands, publications, and digital platforms using design tools and creative thinking.', '{"R": 0.3, "I": 0.3, "A": 0.95, "S": 0.3, "E": 0.3, "C": 0.4}', ARRAY['Graphic Design', 'Fine Arts', 'Visual Communication', 'Multimedia Design'], ARRAY['Adobe Creative Suite', 'Typography', 'Color Theory', 'Branding'], '$45,000 - $90,000', 'Design & Creative'),
('Entrepreneur / Startup Founder', 'Launch and grow new business ventures. Identify market opportunities and lead teams to execute a vision.', '{"R": 0.4, "I": 0.5, "A": 0.6, "S": 0.5, "E": 0.95, "C": 0.4}', ARRAY['Business Administration', 'Entrepreneurship', 'Marketing', 'Finance'], ARRAY['Leadership', 'Strategic Thinking', 'Fundraising', 'Networking'], 'Variable', 'Business'),
('Teacher / Educator', 'Teach and inspire students at various levels. Develop curriculum and create engaging learning experiences.', '{"R": 0.2, "I": 0.5, "A": 0.5, "S": 0.95, "E": 0.4, "C": 0.5}', ARRAY['Education', 'Subject-Specific Degrees', 'Curriculum Development'], ARRAY['Communication', 'Patience', 'Curriculum Design', 'Mentoring'], '$40,000 - $80,000', 'Education'),
('Mechanical Engineer', 'Design and develop mechanical systems, from consumer products to industrial machinery.', '{"R": 0.95, "I": 0.8, "A": 0.3, "S": 0.2, "E": 0.3, "C": 0.5}', ARRAY['Mechanical Engineering', 'Industrial Engineering', 'Physics'], ARRAY['CAD Software', 'Thermodynamics', 'Materials Science', 'Problem Solving'], '$65,000 - $120,000', 'Engineering'),
('Product Manager', 'Define product vision and strategy. Bridge technical and business teams to deliver user-focused products.', '{"R": 0.3, "I": 0.6, "A": 0.5, "S": 0.6, "E": 0.85, "C": 0.5}', ARRAY['Business Administration', 'Computer Science', 'Marketing', 'Engineering'], ARRAY['Product Strategy', 'User Research', 'Agile', 'Data Analysis'], '$90,000 - $170,000', 'Technology'),
('Social Worker', 'Support individuals and communities in overcoming challenges. Advocate for social justice and well-being.', '{"R": 0.2, "I": 0.4, "A": 0.3, "S": 0.95, "E": 0.4, "C": 0.4}', ARRAY['Social Work', 'Psychology', 'Sociology', 'Public Health'], ARRAY['Case Management', 'Counseling', 'Community Outreach', 'Advocacy'], '$40,000 - $70,000', 'Social Services'),
('Accountant', 'Manage financial records, prepare tax returns, and ensure regulatory compliance for organizations.', '{"R": 0.1, "I": 0.5, "A": 0.1, "S": 0.3, "E": 0.4, "C": 0.95}', ARRAY['Accounting', 'Finance', 'Business Administration'], ARRAY['Tax Preparation', 'Auditing', 'Financial Reporting', 'Attention to Detail'], '$50,000 - $100,000', 'Finance'),
('Architect', 'Design buildings and structures that are functional, safe, and aesthetically pleasing.', '{"R": 0.8, "I": 0.6, "A": 0.9, "S": 0.3, "E": 0.4, "C": 0.5}', ARRAY['Architecture', 'Urban Planning', 'Civil Engineering', 'Fine Arts'], ARRAY['AutoCAD', '3D Modeling', 'Design Thinking', 'Project Management'], '$55,000 - $120,000', 'Architecture'),
('Biomedical Researcher', 'Conduct research to advance understanding of human health and develop new treatments.', '{"R": 0.5, "I": 0.95, "A": 0.2, "S": 0.5, "E": 0.2, "C": 0.6}', ARRAY['Biology', 'Biomedical Sciences', 'Chemistry', 'Biochemistry'], ARRAY['Lab Techniques', 'Data Analysis', 'Scientific Writing', 'Critical Thinking'], '$55,000 - $110,000', 'Healthcare'),
('Sales Director', 'Lead sales teams, develop revenue strategies, and build key client relationships.', '{"R": 0.2, "I": 0.4, "A": 0.3, "S": 0.6, "E": 0.95, "C": 0.5}', ARRAY['Business Administration', 'Marketing', 'Communications'], ARRAY['Negotiation', 'CRM Tools', 'Strategic Planning', 'Team Leadership'], '$80,000 - $180,000', 'Business'),
('Film / Video Producer', 'Oversee the production of films, videos, and multimedia content from concept to completion.', '{"R": 0.5, "I": 0.3, "A": 0.9, "S": 0.4, "E": 0.7, "C": 0.3}', ARRAY['Film Studies', 'Communications', 'Multimedia Production', 'Fine Arts'], ARRAY['Video Editing', 'Storytelling', 'Project Management', 'Budgeting'], '$45,000 - $120,000', 'Media & Entertainment'),
('Supply Chain Manager', 'Optimize logistics, procurement, and distribution processes to ensure efficient operations.', '{"R": 0.5, "I": 0.5, "A": 0.1, "S": 0.3, "E": 0.6, "C": 0.9}', ARRAY['Supply Chain Management', 'Business Administration', 'Logistics', 'Industrial Engineering'], ARRAY['Logistics Planning', 'ERP Systems', 'Negotiation', 'Process Optimization'], '$65,000 - $130,000', 'Operations'),
('Human Resources Manager', 'Manage recruitment, employee relations, training, and organizational culture initiatives.', '{"R": 0.1, "I": 0.4, "A": 0.3, "S": 0.8, "E": 0.7, "C": 0.6}', ARRAY['Human Resources', 'Business Administration', 'Psychology', 'Organizational Development'], ARRAY['Recruitment', 'Employee Relations', 'HRIS', 'Conflict Resolution'], '$60,000 - $120,000', 'Business'),
('Environmental Scientist', 'Study and develop solutions for environmental issues including pollution, conservation, and sustainability.', '{"R": 0.7, "I": 0.9, "A": 0.2, "S": 0.5, "E": 0.3, "C": 0.5}', ARRAY['Environmental Science', 'Biology', 'Chemistry', 'Geology'], ARRAY['Field Research', 'GIS', 'Data Analysis', 'Policy Analysis'], '$50,000 - $100,000', 'Environmental'),
('Creative Director', 'Lead creative teams and define the visual and conceptual direction for brands and campaigns.', '{"R": 0.2, "I": 0.4, "A": 0.95, "S": 0.4, "E": 0.8, "C": 0.3}', ARRAY['Graphic Design', 'Fine Arts', 'Communications', 'Marketing'], ARRAY['Creative Strategy', 'Team Leadership', 'Brand Development', 'Visual Design'], '$80,000 - $160,000', 'Design & Creative'),
('Cybersecurity Analyst', 'Protect organizations from cyber threats by monitoring, analyzing, and responding to security incidents.', '{"R": 0.5, "I": 0.85, "A": 0.2, "S": 0.2, "E": 0.3, "C": 0.8}', ARRAY['Computer Science', 'Cybersecurity', 'Information Technology'], ARRAY['Network Security', 'Penetration Testing', 'SIEM Tools', 'Incident Response'], '$70,000 - $140,000', 'Technology'),
('Nurse Practitioner', 'Provide primary and specialized healthcare, diagnose conditions, and prescribe treatments.', '{"R": 0.6, "I": 0.6, "A": 0.2, "S": 0.95, "E": 0.3, "C": 0.5}', ARRAY['Nursing', 'Health Sciences', 'Pre-Medicine'], ARRAY['Patient Care', 'Clinical Assessment', 'Pharmacology', 'Communication'], '$90,000 - $140,000', 'Healthcare'),
('Management Consultant', 'Advise organizations on strategy, operations, and organizational improvement to drive performance.', '{"R": 0.2, "I": 0.7, "A": 0.3, "S": 0.5, "E": 0.9, "C": 0.6}', ARRAY['Business Administration', 'Economics', 'Finance', 'Engineering'], ARRAY['Problem Solving', 'Data Analysis', 'Presentations', 'Strategy'], '$85,000 - $180,000', 'Consulting');
