
-- Create skill question bank table
CREATE TABLE public.skill_question_bank (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  career_path TEXT NOT NULL,
  skill_name TEXT NOT NULL,
  question TEXT NOT NULL,
  options JSONB NOT NULL DEFAULT '[]'::jsonb,
  correct_index INTEGER NOT NULL,
  explanation TEXT NOT NULL DEFAULT '',
  difficulty TEXT NOT NULL DEFAULT 'foundational',
  module_level INTEGER NOT NULL DEFAULT 1,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Enable RLS
ALTER TABLE public.skill_question_bank ENABLE ROW LEVEL SECURITY;

-- Anyone authenticated can read questions
CREATE POLICY "Authenticated users can read questions"
  ON public.skill_question_bank
  FOR SELECT
  USING (auth.role() = 'authenticated');

-- Create indexes for efficient querying
CREATE INDEX idx_question_bank_career_skill ON public.skill_question_bank (career_path, skill_name);
CREATE INDEX idx_question_bank_difficulty ON public.skill_question_bank (difficulty);

-- Seed: Computer Science
INSERT INTO public.skill_question_bank (career_path, skill_name, question, options, correct_index, explanation, difficulty, module_level) VALUES
-- Programming (modules 1-4)
('Computer Science', 'Programming', 'What is the output of: print(type([]))?', '["<class ''list''>","<class ''tuple''>","<class ''dict''>","<class ''set''>"]', 0, 'In Python, [] creates an empty list, so type([]) returns <class ''list''>.', 'foundational', 1),
('Computer Science', 'Programming', 'Which keyword is used to define a function in Python?', '["func","define","def","function"]', 2, 'Python uses the ''def'' keyword to define functions.', 'foundational', 1),
('Computer Science', 'Programming', 'What is a variable scope?', '["The data type of a variable","The region of code where a variable is accessible","The size of the variable in memory","The name of the variable"]', 1, 'Variable scope determines where in the code a variable can be accessed.', 'foundational', 2),
('Computer Science', 'Programming', 'What does OOP stand for?', '["Object-Oriented Programming","Open Online Platform","Operational Output Process","Organized Object Protocol"]', 0, 'OOP stands for Object-Oriented Programming, a paradigm based on objects and classes.', 'developing', 3),
('Computer Science', 'Programming', 'Which principle states a class should have only one reason to change?', '["Open/Closed Principle","Single Responsibility Principle","Liskov Substitution","Interface Segregation"]', 1, 'The Single Responsibility Principle (SRP) states that a class should have only one reason to change.', 'advanced', 4),

-- Data Structures (modules 5-8)
('Computer Science', 'Data Structures', 'What is the time complexity of accessing an element in an array by index?', '["O(n)","O(log n)","O(1)","O(n²)"]', 2, 'Array access by index is O(1) because arrays use contiguous memory with direct offset calculation.', 'foundational', 5),
('Computer Science', 'Data Structures', 'Which data structure uses FIFO (First In, First Out)?', '["Stack","Queue","Tree","Graph"]', 1, 'A Queue follows FIFO ordering where elements are removed in the order they were added.', 'foundational', 5),
('Computer Science', 'Data Structures', 'What is a linked list?', '["An array with fixed size","A sequence of nodes where each node points to the next","A tree with two children","A hash table"]', 1, 'A linked list is a linear data structure where each element (node) contains data and a reference to the next node.', 'foundational', 6),
('Computer Science', 'Data Structures', 'What is the worst-case time complexity of searching in a binary search tree?', '["O(1)","O(log n)","O(n)","O(n log n)"]', 2, 'In the worst case (unbalanced tree), BST search degrades to O(n).', 'developing', 7),
('Computer Science', 'Data Structures', 'Which data structure would you use to implement an undo feature?', '["Queue","Stack","Array","Linked List"]', 1, 'A Stack (LIFO) is ideal for undo operations—the last action is the first to be undone.', 'developing', 8),

-- Algorithms (modules 9-12)
('Computer Science', 'Algorithms', 'What is the time complexity of binary search?', '["O(n)","O(n²)","O(log n)","O(1)"]', 2, 'Binary search halves the search space each step, resulting in O(log n) complexity.', 'foundational', 9),
('Computer Science', 'Algorithms', 'Which sorting algorithm has the best average-case time complexity?', '["Bubble Sort O(n²)","Merge Sort O(n log n)","Selection Sort O(n²)","Insertion Sort O(n²)"]', 1, 'Merge Sort has O(n log n) average-case complexity, which is optimal for comparison-based sorting.', 'developing', 10),
('Computer Science', 'Algorithms', 'What is dynamic programming?', '["A way to write fast code","Breaking problems into overlapping subproblems and storing results","A type of database query","A programming language feature"]', 1, 'Dynamic programming solves complex problems by breaking them into overlapping subproblems and caching results.', 'advanced', 11),
('Computer Science', 'Algorithms', 'What does Big O notation measure?', '["Exact runtime in seconds","Memory usage only","Upper bound of growth rate","The speed of the CPU"]', 2, 'Big O notation describes the upper bound of an algorithm''s growth rate as input size increases.', 'foundational', 9),
('Computer Science', 'Algorithms', 'Which algorithm technique divides a problem into smaller subproblems, solves each, and combines results?', '["Greedy","Dynamic Programming","Divide and Conquer","Backtracking"]', 2, 'Divide and Conquer splits the problem, solves subproblems recursively, and merges results.', 'developing', 12),

-- Git & Version Control (modules 13-15)
('Computer Science', 'Git & Version Control', 'What command creates a new Git branch?', '["git new branch","git branch <name>","git create <name>","git checkout branch"]', 1, '''git branch <name>'' creates a new branch. Use ''git checkout -b <name>'' to create and switch to it.', 'foundational', 13),
('Computer Science', 'Git & Version Control', 'What is the purpose of a pull request?', '["To download code","To delete a branch","To propose changes and request code review","To push code to production"]', 2, 'A pull request proposes merging changes from one branch to another, enabling code review.', 'foundational', 13),
('Computer Science', 'Git & Version Control', 'What does ''git rebase'' do?', '["Deletes commit history","Moves or combines commits onto a new base","Creates a new repository","Merges two repositories"]', 1, 'Git rebase re-applies commits on top of another base tip, creating a linear history.', 'developing', 14),
('Computer Science', 'Git & Version Control', 'What is a merge conflict?', '["A bug in the code","When two branches modify the same lines and Git cannot auto-merge","A failed deployment","A corrupted repository"]', 1, 'Merge conflicts occur when competing changes are made to the same line of a file.', 'foundational', 14),
('Computer Science', 'Git & Version Control', 'What is the difference between git merge and git rebase?', '["They are the same","Merge creates a merge commit; rebase replays commits linearly","Merge is faster","Rebase deletes branches"]', 1, 'Merge preserves branch history with a merge commit; rebase creates a linear history by replaying commits.', 'advanced', 15),

-- System Design (modules 16-20)
('Computer Science', 'System Design', 'What is horizontal scaling?', '["Adding more RAM to a server","Adding more servers to handle load","Increasing CPU speed","Using a faster database"]', 1, 'Horizontal scaling (scaling out) adds more machines to distribute workload.', 'developing', 16),
('Computer Science', 'System Design', 'What is a load balancer?', '["A database optimizer","A device that distributes network traffic across multiple servers","A caching mechanism","A monitoring tool"]', 1, 'A load balancer distributes incoming traffic across multiple servers to ensure no single server is overwhelmed.', 'foundational', 16),
('Computer Science', 'System Design', 'What is the CAP theorem?', '["A coding standard","States a distributed system can only guarantee 2 of: Consistency, Availability, Partition tolerance","A design pattern","A testing methodology"]', 1, 'The CAP theorem states that in a distributed system, you can only guarantee two of three: Consistency, Availability, and Partition tolerance.', 'advanced', 18),
('Computer Science', 'System Design', 'What is caching?', '["Encrypting data","Storing frequently accessed data in fast storage for quick retrieval","Compressing files","Backing up a database"]', 1, 'Caching stores copies of frequently accessed data in faster storage (like RAM) to reduce latency.', 'foundational', 17),
('Computer Science', 'System Design', 'What is a microservices architecture?', '["A single large application","An architecture where the application is split into small, independent services","A type of database","A frontend framework"]', 1, 'Microservices architecture decomposes an application into small, loosely coupled services that can be developed and deployed independently.', 'developing', 19),

-- Cloud Computing (modules 21-24)
('Computer Science', 'Cloud Computing', 'What does IaaS stand for?', '["Internet as a Service","Infrastructure as a Service","Integration as a Service","Information as a Service"]', 1, 'IaaS (Infrastructure as a Service) provides virtualized computing resources over the internet.', 'foundational', 21),
('Computer Science', 'Cloud Computing', 'What is serverless computing?', '["Computing without any servers","A model where the cloud provider manages server infrastructure automatically","Offline computing","Edge computing"]', 1, 'Serverless computing lets developers run code without managing servers—the provider handles scaling and infrastructure.', 'developing', 22),
('Computer Science', 'Cloud Computing', 'What is a container in cloud computing?', '["A virtual machine","A lightweight, standalone package that includes everything needed to run software","A database type","A network protocol"]', 1, 'Containers package code and dependencies together, ensuring consistent behavior across environments.', 'developing', 23),
('Computer Science', 'Cloud Computing', 'What is the difference between public and private cloud?', '["No difference","Public cloud is shared infrastructure; private cloud is dedicated to one organization","Public is free; private is paid","Public is faster"]', 1, 'Public cloud shares infrastructure among multiple tenants; private cloud is dedicated to a single organization.', 'foundational', 21),
('Computer Science', 'Cloud Computing', 'What is auto-scaling?', '["Manually adding servers","Automatically adjusting compute resources based on demand","Compressing data","Load balancing"]', 1, 'Auto-scaling automatically adjusts the number of computing resources based on current demand.', 'advanced', 24),

-- Data Science
('Data Science', 'Statistics', 'What is the difference between mean and median?', '["They are the same","Mean is the average; median is the middle value when sorted","Mean is always larger","Median is the average"]', 1, 'Mean is the arithmetic average; median is the middle value in a sorted dataset, more robust to outliers.', 'foundational', 1),
('Data Science', 'Statistics', 'What is standard deviation?', '["The average value","A measure of how spread out values are from the mean","The most common value","The range of data"]', 1, 'Standard deviation quantifies the amount of variation or dispersion in a set of values.', 'foundational', 2),
('Data Science', 'Statistics', 'What is a p-value?', '["A probability percentage","The probability of observing results at least as extreme as the actual results, assuming the null hypothesis is true","A prediction score","A performance metric"]', 1, 'A p-value measures the probability of obtaining test results at least as extreme as observed, under the null hypothesis.', 'developing', 3),
('Data Science', 'Statistics', 'What is the Central Limit Theorem?', '["Large datasets are always normal","The sampling distribution of the mean approaches a normal distribution as sample size increases","All data is centered","Mean equals median"]', 1, 'CLT states that the distribution of sample means approximates a normal distribution as the sample size gets larger.', 'advanced', 4),
('Data Science', 'Statistics', 'What is correlation vs causation?', '["They are the same thing","Correlation measures association; causation implies one variable directly affects another","Causation is weaker than correlation","Neither is measurable"]', 1, 'Correlation indicates a statistical relationship between two variables; causation means one directly causes the other.', 'foundational', 2),

('Data Science', 'Machine Learning', 'What is the difference between supervised and unsupervised learning?', '["No difference","Supervised uses labeled data; unsupervised finds patterns in unlabeled data","Supervised is faster","Unsupervised is more accurate"]', 1, 'Supervised learning trains on labeled data to predict outcomes; unsupervised learning discovers hidden patterns without labels.', 'foundational', 5),
('Data Science', 'Machine Learning', 'What is overfitting?', '["When a model is too simple","When a model performs well on training data but poorly on new data","When a model is too slow","When data is missing"]', 1, 'Overfitting occurs when a model learns noise in the training data, reducing its ability to generalize.', 'developing', 6),
('Data Science', 'Machine Learning', 'What is a confusion matrix?', '["A complex algorithm","A table showing predicted vs actual classifications","A type of neural network","A data cleaning tool"]', 1, 'A confusion matrix visualizes the performance of a classification model by comparing predicted and actual labels.', 'developing', 7),
('Data Science', 'Machine Learning', 'What is cross-validation?', '["Testing on training data","A technique that splits data into folds to train and validate the model multiple times","A type of neural network","Data augmentation"]', 1, 'Cross-validation partitions data into subsets, trains on some and validates on others, to assess model generalization.', 'advanced', 8),
('Data Science', 'Machine Learning', 'What is feature engineering?', '["Deleting columns","Creating new input variables from existing data to improve model performance","A type of deep learning","Database optimization"]', 1, 'Feature engineering transforms raw data into features that better represent the underlying problem to improve model accuracy.', 'developing', 7),

('Data Science', 'Python for Data Science', 'What library is commonly used for data manipulation in Python?', '["NumPy","Pandas","Flask","Django"]', 1, 'Pandas provides DataFrames and Series for efficient data manipulation and analysis in Python.', 'foundational', 9),
('Data Science', 'Python for Data Science', 'What does df.describe() return in Pandas?', '["The column names","Summary statistics (count, mean, std, min, max, etc.)","The data types","The first 5 rows"]', 1, 'df.describe() generates descriptive statistics including count, mean, std, min, percentiles, and max.', 'foundational', 9),
('Data Science', 'Python for Data Science', 'What is a NumPy array?', '["A Python list","A multi-dimensional, fixed-type container for efficient numerical computation","A database table","A dictionary"]', 1, 'NumPy arrays are homogeneous, multi-dimensional arrays optimized for fast numerical operations.', 'foundational', 10),
('Data Science', 'Python for Data Science', 'How do you handle missing values in Pandas?', '["Ignore them","Use fillna(), dropna(), or interpolate()","Delete the entire dataset","Replace with zeros only"]', 1, 'Pandas provides fillna() to replace, dropna() to remove, and interpolate() to estimate missing values.', 'developing', 11),
('Data Science', 'Python for Data Science', 'What is the purpose of matplotlib?', '["Data cleaning","Creating static, animated, and interactive visualizations","Machine learning","Web development"]', 1, 'Matplotlib is Python''s primary library for creating plots, charts, and other data visualizations.', 'foundational', 10),

('Data Science', 'Data Visualization', 'What is the purpose of a scatter plot?', '["Showing categories","Displaying the relationship between two continuous variables","Showing time series","Displaying proportions"]', 1, 'Scatter plots show the relationship between two continuous variables, revealing patterns, clusters, or correlations.', 'foundational', 13),
('Data Science', 'Data Visualization', 'When should you use a bar chart vs a pie chart?', '["Always use pie charts","Bar charts for comparing categories; pie charts for showing proportions of a whole","They are interchangeable","Neither is useful"]', 1, 'Bar charts are better for comparing values across categories; pie charts show parts of a whole (best with few categories).', 'foundational', 13),
('Data Science', 'Data Visualization', 'What is a heatmap used for?', '["Navigation","Showing the magnitude of values in a matrix using color intensity","Time series analysis","Text analysis"]', 1, 'Heatmaps use color to represent values in a matrix, useful for correlation matrices and frequency tables.', 'developing', 14),
('Data Science', 'Data Visualization', 'What is the principle of ''data-ink ratio''?', '["Use as much ink as possible","Maximize the proportion of ink used to present data vs non-data elements","Use only black ink","Minimize all chart elements"]', 1, 'Edward Tufte''s data-ink ratio principle suggests maximizing the share of ink devoted to presenting data information.', 'advanced', 15),
('Data Science', 'Data Visualization', 'What makes a misleading chart?', '["Using colors","Truncated axes, inconsistent scales, or cherry-picked data ranges","Having a title","Using legends"]', 2, 'Misleading charts often truncate y-axes, use inconsistent scales, or selectively present data to distort perception.', 'developing', 14),

('Data Science', 'SQL & Databases', 'What does SELECT * FROM users WHERE age > 25 return?', '["All users","Users older than 25","Users exactly 25","Users younger than 25"]', 1, 'The WHERE clause filters rows where the age column is greater than 25.', 'foundational', 17),
('Data Science', 'SQL & Databases', 'What is a JOIN in SQL?', '["Deleting tables","Combining rows from two or more tables based on a related column","Creating indexes","Backing up data"]', 1, 'A JOIN combines rows from multiple tables based on a related column between them.', 'foundational', 17),
('Data Science', 'SQL & Databases', 'What is the difference between INNER JOIN and LEFT JOIN?', '["No difference","INNER returns only matching rows; LEFT returns all rows from the left table plus matches","LEFT is faster","INNER includes NULLs"]', 1, 'INNER JOIN returns only rows with matches in both tables; LEFT JOIN returns all left table rows, with NULLs for non-matches.', 'developing', 18),
('Data Science', 'SQL & Databases', 'What is database normalization?', '["Making the database faster","Organizing data to reduce redundancy and improve integrity","Deleting duplicate tables","Compressing data"]', 1, 'Normalization organizes a database to minimize redundancy and dependency by dividing tables and defining relationships.', 'developing', 19),
('Data Science', 'SQL & Databases', 'What is an index in a database?', '["A table of contents for a book","A data structure that improves the speed of data retrieval operations","A primary key","A foreign key"]', 1, 'A database index is a data structure that improves query speed by allowing faster lookups on specific columns.', 'advanced', 20),

('Data Science', 'Deep Learning', 'What is a neural network?', '["A database","A computing system inspired by biological neural networks, composed of layers of interconnected nodes","A sorting algorithm","A web framework"]', 1, 'Neural networks are computing systems with layers of interconnected nodes (neurons) that process data through weighted connections.', 'foundational', 21),
('Data Science', 'Deep Learning', 'What is an activation function?', '["A startup function","A function that determines the output of a neural network node","A data cleaning step","A loss function"]', 1, 'Activation functions introduce non-linearity, determining whether a neuron should be activated based on its input.', 'developing', 22),
('Data Science', 'Deep Learning', 'What is backpropagation?', '["Moving data backwards","An algorithm that calculates gradients to update weights by propagating errors backward through the network","A data backup","Reversing predictions"]', 1, 'Backpropagation computes the gradient of the loss function with respect to each weight by propagating errors backward.', 'advanced', 23),
('Data Science', 'Deep Learning', 'What is a CNN used for?', '["Text generation","Image recognition and computer vision tasks","Database queries","Web scraping"]', 1, 'Convolutional Neural Networks (CNNs) excel at processing grid-like data, especially images, through convolutional layers.', 'developing', 22),
('Data Science', 'Deep Learning', 'What is transfer learning?', '["Moving data between databases","Reusing a pre-trained model on a new, related task to leverage existing knowledge","Copying code","Data migration"]', 1, 'Transfer learning applies knowledge gained from one task to a different but related task, reducing training time and data needs.', 'advanced', 24),

-- Business Administration
('Business Administration', 'Financial Analysis', 'What is a balance sheet?', '["A profit report","A financial statement showing assets, liabilities, and equity at a specific point in time","A cash flow report","A budget plan"]', 1, 'A balance sheet provides a snapshot of what a company owns (assets), owes (liabilities), and the shareholders'' equity.', 'foundational', 1),
('Business Administration', 'Financial Analysis', 'What is ROI?', '["Revenue Over Income","Return on Investment—a measure of profitability relative to cost","Rate of Interest","Risk of Investment"]', 1, 'ROI measures the profitability of an investment as a percentage: (Net Profit / Cost of Investment) × 100.', 'foundational', 2),
('Business Administration', 'Financial Analysis', 'What is the difference between revenue and profit?', '["They are the same","Revenue is total income; profit is revenue minus expenses","Profit is always higher","Revenue includes tax"]', 1, 'Revenue is total income from sales; profit is what remains after subtracting all costs and expenses.', 'foundational', 1),
('Business Administration', 'Financial Analysis', 'What is EBITDA?', '["A tax form","Earnings Before Interest, Taxes, Depreciation, and Amortization","A type of equity","An accounting method"]', 1, 'EBITDA measures a company''s overall financial performance as an alternative to net income.', 'developing', 3),
('Business Administration', 'Financial Analysis', 'What is a break-even analysis?', '["A risk assessment","Determining the point where total revenue equals total costs","A marketing strategy","A hiring plan"]', 1, 'Break-even analysis identifies the sales volume at which total revenues equal total costs, resulting in zero profit or loss.', 'developing', 4),

('Business Administration', 'Strategic Planning', 'What is a SWOT analysis?', '["A financial tool","An assessment of Strengths, Weaknesses, Opportunities, and Threats","A marketing metric","A hiring framework"]', 1, 'SWOT analysis evaluates internal strengths/weaknesses and external opportunities/threats to inform strategic decisions.', 'foundational', 5),
('Business Administration', 'Strategic Planning', 'What is a mission statement?', '["A financial report","A declaration of an organization''s core purpose and focus","A legal document","An operational plan"]', 1, 'A mission statement defines the organization''s purpose, what it does, whom it serves, and how.', 'foundational', 5),
('Business Administration', 'Strategic Planning', 'What is competitive advantage?', '["Being the cheapest","A condition that allows a company to outperform its competitors","Having the most employees","Being the oldest company"]', 1, 'Competitive advantage is a set of unique qualities that enable a company to generate greater value than its rivals.', 'developing', 7),
('Business Administration', 'Strategic Planning', 'What is Porter''s Five Forces model?', '["A leadership model","A framework analyzing competitive forces: rivalry, new entrants, substitutes, buyer power, supplier power","A financial ratio","A marketing framework"]', 1, 'Porter''s Five Forces analyzes the competitive environment through five key forces that shape industry competition.', 'advanced', 8),
('Business Administration', 'Strategic Planning', 'What is a KPI?', '["A company type","A Key Performance Indicator—a measurable value that demonstrates how effectively goals are achieved","A financial regulation","A job title"]', 1, 'KPIs are quantifiable metrics used to evaluate success in meeting strategic and operational goals.', 'foundational', 6),

('Business Administration', 'Project Management', 'What is a Gantt chart?', '["A financial report","A visual timeline showing project tasks, durations, and dependencies","A organizational chart","A flow diagram"]', 1, 'A Gantt chart is a bar chart that illustrates a project schedule, showing task timelines and dependencies.', 'foundational', 9),
('Business Administration', 'Project Management', 'What are the five phases of project management?', '["Plan, Do, Check, Act, Review","Initiation, Planning, Execution, Monitoring & Controlling, Closing","Idea, Build, Test, Launch, Maintain","Research, Design, Develop, Test, Deploy"]', 1, 'The five phases are: Initiation, Planning, Execution, Monitoring & Controlling, and Closing.', 'foundational', 9),
('Business Administration', 'Project Management', 'What is scope creep?', '["A type of budget","Uncontrolled expansion of project scope without adjustments to time, cost, or resources","A testing method","A staffing issue"]', 1, 'Scope creep occurs when project requirements expand beyond the original plan without corresponding changes to resources.', 'developing', 11),
('Business Administration', 'Project Management', 'What is the critical path method?', '["The shortest task list","A technique to identify the longest sequence of dependent tasks determining project duration","A budget method","A hiring process"]', 1, 'The critical path is the longest sequence of dependent tasks; any delay on this path delays the entire project.', 'advanced', 12),
('Business Administration', 'Project Management', 'What is Agile methodology?', '["A strict waterfall approach","An iterative approach to project management emphasizing flexibility, collaboration, and continuous improvement","A financial method","A hiring strategy"]', 1, 'Agile is an iterative approach that delivers work in small increments, enabling rapid adaptation to change.', 'developing', 10),

('Business Administration', 'Leadership', 'What is transformational leadership?', '["Micromanaging employees","A leadership style that inspires and motivates followers to exceed expectations through vision and empowerment","Autocratic decision-making","Laissez-faire management"]', 1, 'Transformational leaders inspire followers by creating a shared vision and empowering them to achieve extraordinary outcomes.', 'foundational', 13),
('Business Administration', 'Leadership', 'What is emotional intelligence in leadership?', '["Being emotional at work","The ability to recognize, understand, and manage your own and others'' emotions","Technical expertise","Financial acumen"]', 1, 'Emotional intelligence includes self-awareness, empathy, and social skills—critical for effective leadership.', 'developing', 14),
('Business Administration', 'Leadership', 'What is delegation?', '["Doing everything yourself","Assigning responsibility and authority to team members while maintaining accountability","Avoiding work","Outsourcing"]', 1, 'Effective delegation assigns tasks to team members based on their strengths while maintaining overall accountability.', 'foundational', 13),
('Business Administration', 'Leadership', 'What is servant leadership?', '["Leading from the top","A philosophy where the leader''s primary goal is to serve their team and help them grow","A weak leadership style","Avoiding decisions"]', 1, 'Servant leadership prioritizes the growth and well-being of team members, leading to stronger organizational performance.', 'advanced', 15),
('Business Administration', 'Leadership', 'What is the difference between a manager and a leader?', '["They are the same","Managers focus on processes and tasks; leaders focus on vision, inspiration, and people","Managers earn more","Leaders have more authority"]', 1, 'Managers ensure operational efficiency; leaders inspire people toward a shared vision. Great leaders do both.', 'developing', 14),

('Business Administration', 'Marketing', 'What are the 4 Ps of marketing?', '["People, Process, Planning, Profit","Product, Price, Place, Promotion","Performance, Positioning, Packaging, Promotion","Production, Pricing, Placement, Publicity"]', 1, 'The 4 Ps—Product, Price, Place, Promotion—form the marketing mix framework for strategic decision-making.', 'foundational', 17),
('Business Administration', 'Marketing', 'What is market segmentation?', '["Selling to everyone","Dividing a market into distinct groups of buyers with different needs or characteristics","A pricing strategy","A distribution method"]', 1, 'Market segmentation divides a broad market into subgroups with common needs to target marketing efforts effectively.', 'foundational', 17),
('Business Administration', 'Marketing', 'What is a unique selling proposition (USP)?', '["The lowest price","A factor that differentiates a product from competitors in the eyes of customers","A type of advertisement","A sales technique"]', 1, 'A USP is the unique benefit that makes a product or brand stand out from competitors.', 'developing', 18),
('Business Administration', 'Marketing', 'What is digital marketing?', '["Traditional advertising","Marketing through digital channels like search engines, social media, email, and websites","Print media","Door-to-door sales"]', 1, 'Digital marketing uses online channels and technology to promote products and engage with target audiences.', 'foundational', 18),
('Business Administration', 'Marketing', 'What is customer lifetime value (CLV)?', '["First purchase amount","The total revenue a business can expect from a single customer over their entire relationship","Monthly revenue","Annual profit"]', 1, 'CLV predicts the total value a customer will bring over their entire relationship, guiding acquisition and retention strategies.', 'advanced', 20),

('Business Administration', 'Business Analytics', 'What is descriptive analytics?', '["Predicting the future","Analyzing historical data to understand what has happened","Prescribing actions","Real-time monitoring"]', 1, 'Descriptive analytics examines past data to understand trends and patterns—answering "what happened?"', 'foundational', 21),
('Business Administration', 'Business Analytics', 'What is a dashboard in business analytics?', '["A car component","A visual display of key metrics and data points for monitoring business performance","A database","A spreadsheet"]', 1, 'A dashboard provides an at-a-glance view of KPIs and metrics, enabling quick performance assessment.', 'foundational', 21),
('Business Administration', 'Business Analytics', 'What is predictive analytics?', '["Analyzing past data","Using statistical models and machine learning to forecast future outcomes","Describing current state","Prescribing solutions"]', 1, 'Predictive analytics uses historical data and statistical algorithms to identify the likelihood of future outcomes.', 'developing', 22),
('Business Administration', 'Business Analytics', 'What is A/B testing?', '["Grading system","Comparing two versions of something to determine which performs better","A debugging technique","A coding practice"]', 1, 'A/B testing compares two versions (A and B) to measure which one performs better against a defined metric.', 'developing', 23),
('Business Administration', 'Business Analytics', 'What is the difference between structured and unstructured data?', '["No difference","Structured data is organized in rows/columns; unstructured data lacks a predefined format","Structured is larger","Unstructured is more accurate"]', 1, 'Structured data fits neatly into databases (spreadsheets); unstructured data includes text, images, and videos.', 'foundational', 22),

-- Information Technology
('Information Technology', 'Networking', 'What is an IP address?', '["A website name","A unique numerical label assigned to each device connected to a network","A password","A software application"]', 1, 'An IP address is a unique identifier for a device on a network, enabling communication between devices.', 'foundational', 1),
('Information Technology', 'Networking', 'What is the difference between TCP and UDP?', '["They are the same","TCP is connection-oriented and reliable; UDP is connectionless and faster but less reliable","UDP is more secure","TCP is faster"]', 1, 'TCP guarantees ordered, error-checked delivery; UDP trades reliability for speed, useful for streaming and gaming.', 'developing', 2),
('Information Technology', 'Networking', 'What is DNS?', '["A programming language","Domain Name System—translates domain names to IP addresses","A database type","A security protocol"]', 1, 'DNS translates human-readable domain names (like google.com) into IP addresses that computers use.', 'foundational', 1),
('Information Technology', 'Networking', 'What is a subnet?', '["A small network","A logical subdivision of an IP network that improves performance and security","A type of cable","A wireless protocol"]', 1, 'Subnetting divides a network into smaller segments, improving performance, security, and IP address management.', 'developing', 3),
('Information Technology', 'Networking', 'What is a VPN?', '["A virus","A Virtual Private Network that creates a secure, encrypted connection over a less secure network","A database","A programming tool"]', 1, 'A VPN creates an encrypted tunnel for data transmission, protecting privacy and enabling secure remote access.', 'foundational', 2),

('Information Technology', 'Cybersecurity', 'What is phishing?', '["A hobby","A social engineering attack that tricks users into revealing sensitive information","A type of malware","A firewall"]', 1, 'Phishing uses deceptive emails, messages, or websites to trick victims into sharing passwords, credit card numbers, etc.', 'foundational', 5),
('Information Technology', 'Cybersecurity', 'What is encryption?', '["Deleting data","Converting data into a coded format to prevent unauthorized access","Compressing files","Backing up data"]', 1, 'Encryption transforms readable data into ciphertext using algorithms, ensuring only authorized parties can access it.', 'foundational', 5),
('Information Technology', 'Cybersecurity', 'What is a firewall?', '["A physical wall","A network security system that monitors and controls incoming and outgoing traffic","An antivirus","A backup system"]', 1, 'A firewall acts as a barrier between trusted and untrusted networks, filtering traffic based on security rules.', 'foundational', 6),
('Information Technology', 'Cybersecurity', 'What is multi-factor authentication (MFA)?', '["Using a strong password","A security method requiring two or more verification factors to access an account","A type of encryption","A firewall setting"]', 1, 'MFA adds security layers by requiring multiple verification methods: something you know, have, or are.', 'developing', 7),
('Information Technology', 'Cybersecurity', 'What is a zero-day vulnerability?', '["An old bug","A security flaw unknown to the vendor that attackers can exploit before a fix is available","A patched vulnerability","A minor bug"]', 1, 'Zero-day vulnerabilities are unknown to the software vendor, giving them zero days to fix before potential exploitation.', 'advanced', 8),

('Information Technology', 'Cloud Infrastructure', 'What is the difference between IaaS, PaaS, and SaaS?', '["They are the same","IaaS provides infrastructure, PaaS provides platform tools, SaaS provides complete applications","IaaS is cheapest","SaaS is most complex"]', 1, 'IaaS offers raw compute/storage, PaaS adds development tools/runtime, SaaS delivers complete applications to end users.', 'foundational', 9),
('Information Technology', 'Cloud Infrastructure', 'What is a virtual machine?', '["A physical server","A software emulation of a physical computer that runs its own operating system","A container","A cloud storage bucket"]', 1, 'A virtual machine emulates a complete computer system, allowing multiple OS instances on a single physical machine.', 'foundational', 9),
('Information Technology', 'Cloud Infrastructure', 'What is DevOps?', '["A programming language","A set of practices combining software development and IT operations for faster, more reliable delivery","A cloud provider","A database"]', 1, 'DevOps bridges development and operations through automation, CI/CD, and collaboration for faster software delivery.', 'developing', 11),
('Information Technology', 'Cloud Infrastructure', 'What is a CI/CD pipeline?', '["A data pipeline","Continuous Integration/Continuous Deployment—automated processes for building, testing, and deploying code","A network cable","A security scan"]', 1, 'CI/CD automates the process of integrating code changes, running tests, and deploying to production environments.', 'developing', 12),
('Information Technology', 'Cloud Infrastructure', 'What is infrastructure as code?', '["Writing code on servers","Managing and provisioning infrastructure through machine-readable configuration files instead of manual processes","A coding standard","A database schema"]', 1, 'Infrastructure as Code (IaC) uses declarative files to automate infrastructure provisioning, ensuring consistency and repeatability.', 'advanced', 12),

('Information Technology', 'Database Management', 'What is the difference between SQL and NoSQL databases?', '["They are the same","SQL uses structured tables with relationships; NoSQL uses flexible schemas like documents or key-value pairs","SQL is newer","NoSQL is always faster"]', 1, 'SQL databases are relational with fixed schemas; NoSQL databases offer flexible schemas for unstructured or semi-structured data.', 'foundational', 13),
('Information Technology', 'Database Management', 'What is ACID in database transactions?', '["A chemical property","Atomicity, Consistency, Isolation, Durability—properties ensuring reliable database transactions","A programming concept","A security standard"]', 1, 'ACID properties ensure database transactions are processed reliably: all-or-nothing, consistent, isolated, and permanent.', 'developing', 14),
('Information Technology', 'Database Management', 'What is database replication?', '["Copying a database to a USB","Maintaining copies of a database across multiple servers for reliability and performance","Backing up once","Deleting duplicates"]', 1, 'Database replication copies data across multiple servers, improving availability, fault tolerance, and read performance.', 'developing', 15),
('Information Technology', 'Database Management', 'What is a stored procedure?', '["A saved file","A precompiled collection of SQL statements stored in the database that can be executed as a unit","A backup method","A query log"]', 1, 'Stored procedures are reusable SQL code blocks that encapsulate business logic in the database for efficiency and security.', 'advanced', 16),
('Information Technology', 'Database Management', 'What is data integrity?', '["Data speed","The accuracy, consistency, and reliability of data throughout its lifecycle","Data size","Data format"]', 1, 'Data integrity ensures data remains accurate, consistent, and trustworthy from creation through its entire lifecycle.', 'foundational', 13),

('Information Technology', 'Linux Administration', 'What is the Linux terminal?', '["A graphical interface","A command-line interface for interacting with the operating system","A web browser","A text editor"]', 1, 'The Linux terminal provides a text-based interface for executing commands, managing files, and administering the system.', 'foundational', 17),
('Information Technology', 'Linux Administration', 'What does the chmod command do?', '["Creates files","Changes file permissions to control read, write, and execute access","Deletes files","Moves files"]', 1, 'chmod modifies file permissions, controlling who can read, write, or execute files and directories.', 'foundational', 17),
('Information Technology', 'Linux Administration', 'What is a cron job?', '["A type of virus","A scheduled task that runs automatically at specified intervals","A log file","A network service"]', 1, 'Cron jobs schedule automated command execution at specified times and intervals using crontab configuration.', 'developing', 18),
('Information Technology', 'Linux Administration', 'What is SSH?', '["A programming language","Secure Shell—a protocol for securely accessing and managing remote servers","A file type","A database"]', 1, 'SSH provides encrypted communication for securely connecting to and administering remote servers.', 'foundational', 18),
('Information Technology', 'Linux Administration', 'What is a package manager in Linux?', '["A shipping service","A tool that automates installing, updating, and removing software packages","A file organizer","A system monitor"]', 1, 'Package managers (apt, yum, dnf) handle software installation, updates, and dependency management automatically.', 'developing', 19),

('Information Technology', 'ITIL & Service Management', 'What is ITIL?', '["A programming language","A framework of best practices for IT service management","A database","A security standard"]', 1, 'ITIL (Information Technology Infrastructure Library) provides structured best practices for delivering IT services.', 'foundational', 21),
('Information Technology', 'ITIL & Service Management', 'What is an SLA?', '["A software license","A Service Level Agreement defining the expected level of service between provider and customer","A security log","A type of API"]', 1, 'An SLA is a formal agreement defining service expectations, metrics, and responsibilities between parties.', 'foundational', 21),
('Information Technology', 'ITIL & Service Management', 'What is incident management?', '["Preventing all errors","The process of restoring normal service operation as quickly as possible after an unplanned interruption","Creating incidents","Logging changes"]', 1, 'Incident management aims to restore normal service operations quickly while minimizing business impact.', 'developing', 22),
('Information Technology', 'ITIL & Service Management', 'What is change management in IT?', '["Changing passwords","A systematic approach to handling changes in IT infrastructure to minimize disruption","Upgrading hardware","Hiring new staff"]', 1, 'Change management ensures changes are implemented smoothly through planning, testing, and approval processes.', 'developing', 23),
('Information Technology', 'ITIL & Service Management', 'What is the difference between a problem and an incident in ITIL?', '["They are the same","An incident is an unplanned interruption; a problem is the underlying root cause of incidents","Problems are worse","Incidents are planned"]', 1, 'Incidents are symptoms requiring immediate resolution; problems are root causes requiring investigation and permanent fixes.', 'advanced', 24);
